import 'dart:math';

List<Map<String, dynamic>> initialMessages() {
    return [
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user2",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Name",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user1",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Gayathri",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user2",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Proposal Number",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user1",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "10271000001501",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user2",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Applicant Name",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user1",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Vishal Gaurav Kumar",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user2",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Query ID",
        "type": "text",
        "source": "",
        "size": "",
      },

      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user1",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "QAgriculture/202425/000055002",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user2",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "Raised On",
        "type": "text",
        "source": "",
        "size": "",
      },
      {
        "id": '${Random().nextInt(100000)}',
        "authorId": "user1",
        "createdAt": DateTime.now().subtract(const Duration(minutes: 2)),
        "text": "26/11/2025",
        "type": "text",
        "source": "",
        "size": "",
      },
    ];
  }
